import { Wallet, TrendingUp, CreditCard, Receipt, BarChart3 } from 'lucide-react'
import type { FinancialCategory, CategoryConfig } from './types'

export const categoryConfig: Record<FinancialCategory, CategoryConfig> = {
  asset: {
    title: 'Assets',
    emptyDescription: 'No assets added yet',
    icon: Wallet,
    accent: 'bg-emerald-500',
    // Icon container styles - solid background with subtle shadow
    iconBg: 'bg-emerald-500',
    iconBgLight: 'bg-emerald-100',
    iconColor: 'text-white',
    iconColorLight: 'text-emerald-600',
    gradientBg: 'bg-gradient-to-br from-emerald-500/20 to-emerald-500/5 border-emerald-500/20',
    textColor: 'text-emerald-400',
    textColorLight: 'text-emerald-600',
    progressColor: 'bg-emerald-500',
    singular: 'asset',
    plural: 'assets',
  },
  income: {
    title: 'Annual Income',
    emptyDescription: 'No income added yet',
    icon: TrendingUp,
    accent: 'bg-blue-500',
    iconBg: 'bg-blue-500',
    iconBgLight: 'bg-blue-100',
    iconColor: 'text-white',
    iconColorLight: 'text-blue-600',
    gradientBg: 'bg-gradient-to-br from-blue-500/20 to-blue-500/5 border-blue-500/20',
    textColor: 'text-blue-400',
    textColorLight: 'text-blue-600',
    progressColor: 'bg-blue-500',
    singular: 'income',
    plural: 'income',
  },
  liability: {
    title: 'Liabilities',
    emptyDescription: 'No liabilities added yet',
    icon: CreditCard,
    accent: 'bg-rose-500',
    iconBg: 'bg-rose-500',
    iconBgLight: 'bg-rose-100',
    iconColor: 'text-white',
    iconColorLight: 'text-rose-600',
    gradientBg: 'bg-gradient-to-br from-rose-500/20 to-rose-500/5 border-rose-500/20',
    textColor: 'text-rose-400',
    textColorLight: 'text-rose-600',
    progressColor: 'bg-rose-500',
    singular: 'liability',
    plural: 'liabilities',
  },
  expense: {
    title: 'Annual Expenses',
    emptyDescription: 'No expenses added yet',
    icon: Receipt,
    accent: 'bg-amber-500',
    iconBg: 'bg-amber-500',
    iconBgLight: 'bg-amber-100',
    iconColor: 'text-white',
    iconColorLight: 'text-amber-600',
    gradientBg: 'bg-gradient-to-br from-amber-500/20 to-amber-500/5 border-amber-500/20',
    textColor: 'text-amber-400',
    textColorLight: 'text-amber-600',
    progressColor: 'bg-amber-500',
    singular: 'expense',
    plural: 'expenses',
  },
  investment: {
    title: 'Investments',
    emptyDescription: 'No investments added yet',
    icon: BarChart3,
    accent: 'bg-purple-500',
    iconBg: 'bg-purple-500',
    iconBgLight: 'bg-purple-100',
    iconColor: 'text-white',
    iconColorLight: 'text-purple-600',
    gradientBg: 'bg-gradient-to-br from-purple-500/20 to-purple-500/5 border-purple-500/20',
    textColor: 'text-purple-400',
    textColorLight: 'text-purple-600',
    progressColor: 'bg-purple-500',
    singular: 'investment',
    plural: 'investments',
  },
}
