import { Building2, Home, Landmark, Hammer } from 'lucide-react'
import type { PropertyOption } from '@/app/property-planner/types'

export const propertyOptions: PropertyOption[] = [
  {
    id: 'hdb-resale',
    title: 'HDB Resale',
    subtitle: 'Immediate move-in',
    description: 'Purchase an existing HDB flat on the resale market with established amenities.',
    icon: <Home className="w-6 h-6" />,
    color: 'from-emerald-500/20 to-emerald-600/5',
    accentColor: 'text-emerald-400',
    priceRange: '$300K - $800K',
    highlights: ['No wait time', 'CPF eligible', 'Grants available'],
  },
  {
    id: 'hdb-bto',
    title: 'HDB BTO',
    subtitle: 'Build-to-Order',
    description: 'Apply for a new HDB flat with 3-5 year waiting period and government subsidies.',
    icon: <Building2 className="w-6 h-6" />,
    color: 'from-blue-500/20 to-blue-600/5',
    accentColor: 'text-blue-400',
    priceRange: '$200K - $600K',
    highlights: ['Subsidized pricing', 'New condition', '3-5 year wait'],
  },
  {
    id: 'ec',
    title: 'Executive Condo',
    subtitle: 'Hybrid property',
    description: 'Private condo with HDB-like subsidies. Privatizes after 10 years.',
    icon: <Landmark className="w-6 h-6" />,
    color: 'from-violet-500/20 to-violet-600/5',
    accentColor: 'text-violet-400',
    priceRange: '$1M - $1.8M',
    highlights: ['Condo facilities', 'EC grants', '5yr MOP'],
  },
  {
    id: 'private-resale',
    title: 'Private Resale',
    subtitle: 'Secondary market',
    description: 'Existing private apartment or condo with immediate availability.',
    icon: <Building2 className="w-6 h-6" />,
    color: 'from-amber-500/20 to-amber-600/5',
    accentColor: 'text-amber-400',
    priceRange: '$1M - $3M+',
    highlights: ['Immediate', 'No restrictions', 'Negotiable'],
  },
  {
    id: 'private-new',
    title: 'New Launch',
    subtitle: 'Developer sale',
    description: 'Brand new private condo directly from developers with latest designs.',
    icon: <Hammer className="w-6 h-6" />,
    color: 'from-rose-500/20 to-rose-600/5',
    accentColor: 'text-rose-400',
    priceRange: '$1.5M - $5M+',
    highlights: ['New warranty', 'Modern design', '1-4yr wait'],
  },
]
