// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat": {
            "post": {
                "description": "Process a chat message and generate AI response with financial tool calls",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Send a chat message",
                "parameters": [
                    {
                        "description": "Chat message",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/financial/actions/dispatch": {
            "post": {
                "description": "Execute approved financial actions from a chat session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actions"
                ],
                "summary": "Execute financial actions",
                "parameters": [
                    {
                        "description": "Actions to execute",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DispatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DispatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/financial/timeline": {
            "get": {
                "description": "Returns the full financial timeline with optional resolution and scenario filtering. Automatically initializes user financial data (default settings, growth configs, cash account) on first access if not already set up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Timeline"
                ],
                "summary": "Get financial timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resolution override (yearly or monthly)",
                        "name": "resolution",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include scenario impacts",
                        "name": "include_scenarios",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of scenario IDs",
                        "name": "scenario_ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/timeline.TimelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/financial/timeline/{year}": {
            "put": {
                "description": "Upserts financial data edits for a given year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Timeline"
                ],
                "summary": "Update financial data for a specific year",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Year (absolute)",
                        "name": "year",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Year edits",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/timeline.TimelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get the health status of the application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/scenario-events": {
            "get": {
                "description": "List all scenario events or create a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scenario Events"
                ],
                "summary": "List or create scenario events",
                "parameters": [
                    {
                        "description": "New scenario event",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.scenarioEventInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repository.ScenarioEvent"
                            }
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/repository.ScenarioEvent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "List all scenario events or create a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scenario Events"
                ],
                "summary": "List or create scenario events",
                "parameters": [
                    {
                        "description": "New scenario event",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.scenarioEventInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repository.ScenarioEvent"
                            }
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/repository.ScenarioEvent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tools": {
            "get": {
                "description": "Returns a list of all available financial tools and their metadata",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get available financial tools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "financial.ImpactEstimate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "monthly_change": {
                    "type": "number"
                },
                "net_worth_change": {
                    "type": "number"
                }
            }
        },
        "financial.ProposedAction": {
            "type": "object",
            "properties": {
                "call_id": {
                    "type": "string"
                },
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "estimated_impact": {
                    "$ref": "#/definitions/financial.ImpactEstimate"
                },
                "friendly_description": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "tool_name": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/financial.Warning"
                    }
                }
            }
        },
        "financial.Warning": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "severity": {
                    "description": "\"low\", \"medium\", \"high\"",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handlers.ChatRequest": {
            "type": "object",
            "required": [
                "chat_id",
                "message",
                "session_id"
            ],
            "properties": {
                "chat_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "handlers.ChatResponse": {
            "type": "object",
            "properties": {
                "actions_executed": {
                    "type": "integer"
                },
                "api_version": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "conversation_flow": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/session.ConversationStep"
                    }
                },
                "message_id": {
                    "type": "string"
                },
                "proposed_actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/financial.ProposedAction"
                    }
                },
                "requires_approval": {
                    "type": "boolean"
                }
            }
        },
        "handlers.DispatchRequest": {
            "type": "object",
            "required": [
                "selected_actions",
                "session_id"
            ],
            "properties": {
                "selected_actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SelectedAction"
                    }
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "handlers.DispatchResponse": {
            "type": "object",
            "properties": {
                "api_version": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ExecutionResult"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/handlers.ExecutionSummary"
                },
                "updated_session_state": {
                    "$ref": "#/definitions/session.SessionState"
                }
            }
        },
        "handlers.ExecutionResult": {
            "type": "object",
            "properties": {
                "call_id": {
                    "type": "string"
                },
                "entity_id": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "execution_time_ms": {
                    "type": "integer"
                },
                "rolled_back": {
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "handlers.ExecutionSummary": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "status": {
                    "description": "\"success\", \"partial_success\", \"failed\"",
                    "type": "string"
                },
                "successful": {
                    "type": "integer"
                },
                "total_actions": {
                    "type": "integer"
                },
                "total_execution_time_ms": {
                    "type": "integer"
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.SelectedAction": {
            "type": "object",
            "required": [
                "call_id"
            ],
            "properties": {
                "approved": {
                    "type": "boolean"
                },
                "call_id": {
                    "type": "string"
                },
                "modified_args": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "handlers.scenarioEventInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "displayColor": {
                    "type": "string"
                },
                "displayIcon": {
                    "type": "string"
                },
                "display_color": {
                    "type": "string"
                },
                "display_icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "impacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.scenarioImpactInput"
                    }
                },
                "isIncluded": {
                    "type": "boolean"
                },
                "is_included": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "occursOn": {
                    "type": "string"
                },
                "occurs_on": {
                    "type": "string"
                },
                "scenarioId": {
                    "type": "string"
                },
                "scenario_id": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.scenarioImpactInput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "cadence": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "endMonth": {
                    "type": "string"
                },
                "end_month": {
                    "type": "string"
                },
                "impactKind": {
                    "type": "string"
                },
                "impact_kind": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "startMonth": {
                    "type": "string"
                },
                "start_month": {
                    "type": "string"
                },
                "targetId": {
                    "type": "string"
                },
                "targetType": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "target_type": {
                    "type": "string"
                }
            }
        },
        "llm.ChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Message content",
                    "type": "string"
                },
                "name": {
                    "description": "Optional name for tool messages",
                    "type": "string"
                },
                "role": {
                    "description": "\"user\", \"assistant\", \"system\", \"tool\"",
                    "type": "string"
                },
                "tool_call_id": {
                    "description": "ID of tool call this message responds to",
                    "type": "string"
                },
                "tool_calls": {
                    "description": "Tool calls in this message",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/llm.ToolCall"
                    }
                }
            }
        },
        "llm.FunctionCall": {
            "type": "object",
            "properties": {
                "arguments": {
                    "description": "JSON string of function arguments",
                    "type": "string"
                },
                "name": {
                    "description": "Function name (e.g., \"create_asset\")",
                    "type": "string"
                }
            }
        },
        "llm.ToolCall": {
            "type": "object",
            "properties": {
                "function": {
                    "description": "Function details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/llm.FunctionCall"
                        }
                    ]
                },
                "id": {
                    "description": "Unique identifier for this tool call",
                    "type": "string"
                },
                "type": {
                    "description": "Always \"function\" for function calls",
                    "type": "string"
                }
            }
        },
        "repository.ScenarioEvent": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "displayColor": {
                    "type": "string"
                },
                "displayIcon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "impacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.ScenarioImpact"
                    }
                },
                "isIncluded": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "occursOn": {
                    "type": "string"
                },
                "scenarioID": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "repository.ScenarioImpact": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "format": "int64"
                },
                "cadence": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "endMonth": {
                    "type": "string"
                },
                "eventID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "impactKind": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "startMonth": {
                    "type": "string"
                },
                "targetID": {
                    "type": "string"
                },
                "targetType": {
                    "type": "string"
                }
            }
        },
        "session.ConversationStep": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "result": {
                    "type": "object",
                    "additionalProperties": true
                },
                "step_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tool_name": {
                    "type": "string"
                },
                "type": {
                    "description": "\"user_message\", \"llm_response\", \"tool_execution\"",
                    "type": "string"
                }
            }
        },
        "session.PendingToolCall": {
            "type": "object",
            "properties": {
                "call_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "friendly_description": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "preview": {
                    "type": "string"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "session.SessionState": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "string"
                },
                "conversation_flow": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/session.ConversationStep"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "last_asset_id": {
                    "type": "string"
                },
                "last_liability_id": {
                    "type": "string"
                },
                "last_property_plan_id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/llm.ChatMessage"
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "pending_actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/session.PendingToolCall"
                    }
                },
                "session_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "timeline.EventImpactSummary": {
            "type": "object",
            "properties": {
                "amountAnnual": {
                    "description": "annualized",
                    "type": "number"
                },
                "amountMonthly": {
                    "type": "number"
                },
                "cadence": {
                    "type": "string"
                },
                "eventId": {
                    "type": "string"
                },
                "impactKind": {
                    "description": "override|delta|start|stop",
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "timeline.GrowthApplied": {
            "type": "object",
            "properties": {
                "annualRatePct": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                }
            }
        },
        "timeline.ItemType": {
            "type": "string",
            "enum": [
                "asset",
                "liability",
                "income",
                "expense",
                "cash_account"
            ],
            "x-enum-varnames": [
                "ItemTypeAsset",
                "ItemTypeLiability",
                "ItemTypeIncome",
                "ItemTypeExpense",
                "ItemTypeCashAccount"
            ]
        },
        "timeline.TimelineItem": {
            "type": "object",
            "properties": {
                "adjAnnualAmt": {
                    "type": "number"
                },
                "adjMonthlyAmt": {
                    "description": "Adjusted monthly amount",
                    "type": "number"
                },
                "amountAnnual": {
                    "type": "number"
                },
                "amountMonthly": {
                    "description": "Monthly amount (when resolution is monthly)",
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "createdMonth": {
                    "description": "Month when created (1-12)",
                    "type": "integer"
                },
                "createdYear": {
                    "type": "integer"
                },
                "eventImpacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.EventImpactSummary"
                    }
                },
                "growthRate": {
                    "description": "GrowthRate is the per-item annual growth rate (percentage)",
                    "type": "number"
                },
                "isAccumulator": {
                    "description": "IsAccumulator indicates this is the designated cash account receiving net savings (cash accounts only)",
                    "type": "boolean"
                },
                "itemId": {
                    "description": "ItemID is the stable logical identifier used for scenario matching (parent_id if present, else row id).",
                    "type": "string"
                },
                "itemType": {
                    "$ref": "#/definitions/timeline.ItemType"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "description": "ParentID is the original/base item id when this row is a child; else same as RowID.",
                    "type": "string"
                },
                "rowId": {
                    "description": "RowID is the concrete finance_* row id (for debugging/reference).",
                    "type": "string"
                },
                "sourceAmount": {
                    "type": "number"
                },
                "sourceFrequency": {
                    "type": "string"
                }
            }
        },
        "timeline.TimelineMonth": {
            "type": "object",
            "properties": {
                "accumulatedCashEnd": {
                    "type": "number"
                },
                "accumulatedCashStart": {
                    "type": "number"
                },
                "accumulatorAccountId": {
                    "type": "string"
                },
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "cashAccounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "growthApplied": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.GrowthApplied"
                    }
                },
                "hasOverrides": {
                    "type": "boolean"
                },
                "income": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "interestEarned": {
                    "type": "number"
                },
                "liabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "month": {
                    "description": "Month number (1-12)",
                    "type": "integer"
                },
                "monthIndex": {
                    "description": "0-based global month index",
                    "type": "integer"
                },
                "monthlyNetSavings": {
                    "description": "Monthly cash accumulation tracking",
                    "type": "number"
                },
                "netCash": {
                    "description": "Monthly net savings",
                    "type": "number"
                },
                "netWorth": {
                    "type": "number"
                },
                "year": {
                    "description": "Calendar year (e.g., 2025)",
                    "type": "integer"
                },
                "yearIndex": {
                    "description": "0-based year index",
                    "type": "integer"
                }
            }
        },
        "timeline.TimelineResponse": {
            "type": "object",
            "properties": {
                "months": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineMonth"
                    }
                },
                "resolution": {
                    "description": "\"yearly\" or \"monthly\"",
                    "type": "string"
                },
                "scenariosApplied": {
                    "description": "ScenariosApplied lists scenario IDs merged into this response (optional).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                },
                "years": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineYear"
                    }
                }
            }
        },
        "timeline.TimelineYear": {
            "type": "object",
            "properties": {
                "accumulatedCashEnd": {
                    "description": "Cash balance at end of year (after interest)",
                    "type": "number"
                },
                "accumulatedCashStart": {
                    "description": "Cash balance at start of year",
                    "type": "number"
                },
                "accumulatorAccountId": {
                    "description": "ID of the accumulator cash account",
                    "type": "string"
                },
                "annualNetSavings": {
                    "description": "Cash accumulation tracking",
                    "type": "number"
                },
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "cashAccounts": {
                    "description": "Cash accounts from cash_accounts table",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "growthApplied": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.GrowthApplied"
                    }
                },
                "hasOverrides": {
                    "type": "boolean"
                },
                "income": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "interestEarned": {
                    "description": "Interest earned this year on accumulator",
                    "type": "number"
                },
                "liabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeline.TimelineItem"
                    }
                },
                "netCash": {
                    "description": "Income - Expenses (annual net savings)",
                    "type": "number"
                },
                "netWorth": {
                    "description": "Assets + CashAccounts - Liabilities",
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "AuthToken": {
            "description": "JWT token for production authentication (HMAC-signed with BACKEND_SHARED_SECRET)",
            "type": "apiKey",
            "name": "X-Auth-Token",
            "in": "header"
        },
        "SessionID": {
            "description": "User/Session ID for development mode authentication",
            "type": "apiKey",
            "name": "X-Session-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Financial Chat System API",
	Description:      "API for managing financial data, chat interactions, and scenario planning",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
